apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-function
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lambda-function
  template:
    metadata:
      labels:
        app: lambda-function
    spec:
      containers:
        - name: lambda-container
          image: lambda-registry:5000/lambda-function
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080