apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: monitoring
spec:
  selector:
    app: fluentd
  ports:
    - protocol: TCP
      port: 24231
      targetPort: 24231
  type: ClusterIP
